### ISSUE TITLE
Additional specifications

### ISSUE THREAD

**Issue by schbrownie** [kickstarter/kickstarter-autodesk-3d#7]
Specifically regarding the FFF (FDM) comparison, if the goal is to get an apples-to-apples comparison between printers, then we should also specify the nozzle diameter and layer height to be used.

**Comment by andreasbastian** [comment]
See my comment on Issue #10 for a bit of background, but the goal here is to just get a comparison of the complete system (hardware + software + electronics) while holding material constant.  By changing which variables you are holding constant and which you are observing, you can learn a lot with these types of geometries, but again, the scope here is at the "product level" rather than the subsystem level of extruders, stepper drivers, and other process parameters.
